version: '2017-09-20'

dependencies:
  - id: java
    type: docker
    ref: container-registry.zalando.net/library/eclipse-temurin-8-jdk

pipeline:
- id: build
  env:
    LEIN_ROOT: true
  type: script
  vm_config:
    type: linux
    image: "cdp-runtime/jdk8-clojure"
  artifacts:
  - type: docs
    name: automata-databases
    path: schema
  commands:
  - desc: Run unit tests
    cmd: |
      git gh-comment test
